# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ppmTool
    ports:
      - '3306:3306'